---
title: "EDA"
output: pdf_document
editor_options: 
  chunk_output_type: console

---

```{r}
library(tidyverse)
library(readr)
library(lubridate)
```


```{r}
adoptions <- read_csv("~/Stats 316 S19/Project/adoptions/adoptions.csv")
# For Jack keep the line below for reading in the data
adoptions <- read_csv("adoptions.csv")
```


```{r}
adoptions %>%
  mutate(month = as.factor(month(outcome_date)))%>%
  filter(!is.na(month))%>%
  ggplot() +
  geom_bar(aes(x=month))


adoptions %>%
  mutate(month = month(outcome_date))%>%
  filter(!is.na(month))%>%
  filter(animal_type=="CAT"| animal_type=="DOG"|animal_type=="BIRD")%>%
  ggplot() +
  geom_density(aes(x=month, color=animal_type, fill=animal_type, alpha=.1))+
  scale_x_discrete("month", limits=as.character(1:12))
  

adoptions %>%
  filter(animal_type=="WILDLIFE") %>%
  group_by(animal_breed) %>%
  summarise(n()) %>%
  print(n=32)


adoptions%>%
  filter(dog == 1) %>%
  filter(adopted == 1) %>%
  group_by(outcome_date) %>%
  tally() %>%
  ggplot()+
  geom_histogram(aes(x=n))

adoptions%>%
  filter(dog==1)%>%
  group_by(pitbull)%>%
  summarise(mean(adopted))




```

