---
title: "Multi-Level Model"
author: "Jack Welsh"
date: "May 1, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(readr)
library(lubridate)
library(lme4)
library(kableExtra)
library(knitr)
adoptions <- read_csv("adoptions.csv")
```



Making a slightly smaller dataset
```{r}
just_dog_adoptions=adoptions%>%
  filter(animal_type=="DOG")%>%
  mutate(animal_breed=as.factor(animal_breed))%>%
  mutate(healthy_intake=ifelse(grepl("^HEALTHY.*",intake_condition),1,0),
         contagious_intake=ifelse(grepl(".*[^NON-]CONTAGIOUS", intake_condition),1,0),
         untreatable_intake=ifelse(grepl(".*(UNTREATABLE).*", intake_condition),1,0),
         treatable_intake=ifelse(grepl("^TREATABLE.*", intake_condition),1,0),
         manageable_intake=ifelse(grepl(".*MANAGEABLE.*", intake_condition),1,0),
         rehabitable_intake=ifelse(grepl(".*REHABILITABLE.*", intake_condition),1,0),
         normal_intake=ifelse(grepl(".*NORMAL.*", intake_condition),1,0),
         chip_status = ifelse(chip_status=="SCAN CHIP", 1, 0))%>% #Isaac added this just to see how models change
         mutate(out_dead = outcome_type %in% c("DEAD ON ARRIVAL", "EUTHANIZED", "DIED"),
         summer = ifelse(month %in% c(5, 6, 7, 8, 9), 1, 0))
```

### Look for correlation by council district

```{r}
just_dog_adoptions %>%
  group_by(council_district)%>%
  summarise(prop_dead = sum(out_dead)/n())%>%
  filter(!is.na(council_district)) %>%
  ggplot(aes(x=as.factor(council_district), y = prop_dead)) +
  geom_bar(stat = "identity")
```

```{r}
just_dog_adoptions %>%
  group_by(council_district)%>%
  summarise(prop_adopted = sum(adopted)/n())%>%
  filter(!is.na(council_district)) %>%
  ggplot(aes(x=as.factor(council_district), y = prop_adopted)) +
  geom_bar(stat = "identity")
```


Random Intercepts
```{r}
mod.1=glmer(adopted~1+(1|animal_breed), data=just_dog_adoptions, family = "binomial")
summary(mod.1)

mod.1=glmer(adopted~1+(1|council_district), data=just_dog_adoptions, family = "binomial")
summary(mod.1)

```



```{r}
mod.2.adopted=glmer(adopted~summer+chip_status+treatable_intake+(1|council_district), data=just_dog_adoptions, family = "binomial")
summary(mod.2.adopted)

mod.2.dead=glmer(out_dead~summer+chip_status+treatable_intake+(1|council_district), data=just_dog_adoptions, family = "binomial")
summary(mod.2.dead)

```




