---
title: "Project Stage 1"
authors: "Isaac Slagel and Jack Welsch"
output: pdf_document
---

1. Identify the important research question(s) which will guide your project (e.g. What factors are associated with lower BMI?) – and describe why your chosen project is interesting to you.  Provide rationale for each variable included in your proposed data set (e.g. Does taking a PE class help?  We may subgroup by gender.  We need to control for diet.)

What factors influence how long an animal will stay in the human shelter? Are certain breeds euthanized at a higher rate than others? Are certain animals adopted more during certain times of the year (ex. are more rabbits adopted around easter?). What differences do we between the condition of dogs and cats in the humane society? This project of interet to us because we love animals and are intrigued in the manner different animals are handled in the humane shelter system. The dataset we found to look into this made us even more motivated to look into these question as it is detailed and clean! 

The variables `animal_breed`, `animal_origin`, `animal_type`, and `chip_status` are all important variables to our observational units. We may end up subtyping by any of these variables. Information on `council_district` provides a possible source of correlation in our data if we want to do some sort of multilevel modeling. We can glean insight on how animals fare in the animal shelters by the variables `intake_condition`, `intake_date`, `intake_subtype`, `intake_type`, `outcome_condition`, `outcome_date`,`outcome_subtype`, `outcome_type`. We will use these variables to create different reponse metrics that we are interested in (like total shelter days, or euthanized). 




2. Find references for at least two articles in the refereed literature that are relevant to your question of interest. You should avoid articles that are too technical to be relevant to the project or to be informative for the non-specialist (e.g. “Beta 2-adrenergic receptor polymorphisms and haplotypes are associated with airways hyperresponsiveness among nonsmoking men,” Chest, 2004). Articles that appear in the popular press (such as The New York Times or Washington Post) or news articles in journals are not acceptable as refereed references, although they may help motivate ideas for your project.  Be sure you obtain the entire paper and not just an abstract!
	You will eventually use these references in the introduction of your paper. Pay close attention to the figures, tables, and methods sections of the papers you select as they can give you an idea of what I'll be expecting from you in your final write up.  
	For the project proposal, include the following information:
  
    -	Give the citation for each reference (in APA format or similar) and a link, if appropriate.
    
    - In 1-2 paragraphs, summarize the primary findings and how they relate to your proposal.


3. Complete a variable chart (similar to the one that follows) for your anticipated variables.  A typical list will include 6-10 variables.  List the variable name, variable role if known (response, explanatory, potential confounder), an indication of whether or not the variable is quantitative or categorical, the range of values for each variable, and the units of measurement for each variable (if appropriate). For any variable whose definition is unclear, provide a short definition.  Also mention your observational units; if your data has multilevel structure, provide the level for each variable as well.  As an example, if body mass index (BMI) were the response variable, attending a physical exercise class daily is the explanatory variable, and age is a potential confounder, the first few lines of the chart might read:

```{r, echo = FALSE}

variables <- c("Variable Name", "Variable Role", "Variable Type", "Range of Values", "Units of Measurement")

breed <- c("animal_breed", "explanatory", "categorical", "296 unique breeds", "NA")
origin <- c("animal_origin", "explanatory", "categorical", "4 sources of shelter animals", "NA")
type <- c("animal_type", "explanatory", "categorical", "5 species of animal", "NA")
```

4. Outline how you plan to address your research question(s) with the data you have listed in (3) (e.g. We plan to run multiple linear regression models with BMI as response and daily attendance and age as explanatory variables, possibly examining interactions between the two).




5. Describe how you obtained your data, providing a link if appropriate.  Store your data, properly labeled, as a .csv file in the Project folder of our class folder on the RStudio server.

We accessed our data from the Dallas Open Data website. This website contains many public datasets, including [animal shelter records](https://www.dallasopendata.com/City-Services/Dallas-Animal-Shelter-Data/7h2m-3um5), which anyone can request an access key to and then download. We installed the data, selected the variables of interest to us, and created a .csv file in the CreateDataset.Rmd file. Our dataset is saved as adoptions.csv.  
